name = "IEEEFloats"
uuid = "fa1f7535-4483-49bf-a10f-ff859e69a43f"
author = "Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"
repo = "https://github.com/JeffreySarnoff/IEEEFloats.jl.git"
license = "MIT"
version = "v0.1.0"
desc = "structural introspection on Float16, Float32, Float64 types." 
keywords = ["IEEE754", "floating point", "constants", "types"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
